services:
  wine-planner:
    build: .
    container_name: wine-planner
    user: "1000:1000"
    env_file:
      - .env
    environment:
      - SYNC_SCHEDULE=0 2 * * *
    volumes:
      - ./:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wine-planner.entrypoints: https
      traefik.http.routers.wine-planner.rule: Host(`wine-planner.unibrain.org`)
      traefik.http.routers.wine-planner.tls: 'true'
      traefik.http.services.wine-planner.loadbalancer.server.port: '8080'
    networks:
      - traefik_proxy
    ports:
      - "8089:8080"
    restart: unless-stopped

  run-now:
    build: .
    container_name: wine-planner-run
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    entrypoint: []
    command: ["bash", "/app/fetch_docker.sh"]
    networks:
      - traefik_proxy
    profiles:
      - run-now

networks:
  traefik_proxy:
    external: true
