services:
  wine-planner:
    build: .
    container_name: wine-planner
    ports:
      - "8089:80"
    env_file:
      - .env
    environment:
      - SYNC_SCHEDULE=0 2 * * *
    volumes:
      - ./site:/app/site
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  run-now:
    build: .
    container_name: wine-planner-run
    env_file:
      - .env
    volumes:
      - ./site:/app/site
    dns:
      - 8.8.8.8
      - 8.8.4.4
    entrypoint: []
    command: ["bash", "/app/fetch_docker.sh"]
    profiles:
      - run-now
