services:
  wine-planner:
    build: .
    container_name: wine-planner
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - SYNC_SCHEDULE=0 2 * * *
    restart: unless-stopped

  run-now:
    build: .
    container_name: wine-planner-run
    env_file:
      - .env
    entrypoint: []
    command: ["bash", "/app/fetch_docker.sh"]
    profiles:
      - run-now
